name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS
        run: git lfs checkout

      - name: Setup node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Restore
        run: yarn install --immutable --immutable-cache

      - name: Set version
        run: npm version --no-git-tag-version ${{ github.event.release.tag_name }}

      - name: Publish npmjs.org
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          registry-url: "https://npm.pkg.github.com"

      - name: Publish github
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
